version: '3.5'
services:
  ikakprosto:
    image: node:20-alpine3.19
    container_name: ikakprosto
    working_dir: /usr/src/ikakprosto
    ports:
      - 8080:8080
    command: npm run dev
    volumes:
      - ./:/usr/src/ikakprosto